name: Build and Make release
on:
  push:
    branches:
      - master
jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: hecrj/setup-rust-action@v1
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get install -y libxkbcommon-dev
      - name: Build iced_text_input_sample binary
        run: cargo build --release
      - name: Pack iced_text_input_sample .deb package
        run: cargo deb --no-build --profile release --package iced_text_input_sample
      - name: prepare for pickup package
        run: mv target/debian/*.deb target/debian/sample_ubuntu2204_amd64.deb
      - name: pickup .deb package
        run: cp target/debian/sample_ubuntu2204_amd64.deb sample_ubuntu_2204_amd64.deb
      - name: pickup sample for other linux
        run: cp target/release/iced_text_input_sample sample_linux_amd64
      - name: Archive iced_text_input_sample binary
        uses: actions/upload-artifact@v2
        with:
          name: sample-linux-x64
          paths: |
            sample_linux_amd64
            sample_ubuntu_2204_amd64.deb

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Enable static CRT linkage
        run: |
          mkdir .cargo
          echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
      - name: Run the application without starting the shell
        run: |
          sed -i '1 i\#![windows_subsystem = \"windows\"]' src/main.rs
      - name: Build iced_text_input_sample binary
        run: cargo build --release
      - name: Rename iced_text_input_sample
        run: ren target/release/iced_text_input_sample.exe sample.exe
      - name: Archive iced_text_input_sample binary
        uses: actions/upload-artifact@v2
        with:
          name: sample-windows-x64
          path: target/release/sample.exe
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Build iced_text_input_sample binary
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.14
        run: cargo build --release
      - name: Rename binary
        run: mv target/release/iced_text_input_sample target/release/sample
      - name: pickup binary
        run: cp target/release/sample sample
      - name: Open binary via double-click
        run: chmod +x sample

      - name: Archive iced_text_input_sample binary
        uses: actions/upload-artifact@v2
        with:
          name: sample-macos-x64
          path: sample_macos_x64
  publish_binaries:
    name: Publish binaries.
    runs-on: ubuntu-latest
    needs: [build_windows, build_linux, build_macos]
    steps:
      - name: accept binary from windows builder
        uses: actions/download-artifact@v2
        with:
          name: sample-windows-x64
      - name: accept binary from linux builder
        uses: actions/download-artifact@v2
        with:
          name: sample-linux-x64
      - name: accept binary from windows builder
        uses: actions/download-artifact@v2
        with:
          name: sample-macos-x64
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "sample*"
